#!/bin/bash

#read static variables
inst_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $inst_root/a_env_conf



#allas_conf_path=("/home/kkmattil/allas-cli-utils/allas_conf")
#os_project_name=$OS_PROJECT_NAME
rpath=""
input=""
get_file=""
options=""
target="./"
help=0
packsize=64
create_new=0
user=""


if [[ $1 == "add" || $1 == "list" ||  $1 == "restore" || $1 == "delete" || $1 == "find" || $1 == "files" || $1 == "dump" || $1 == "unlock" ]]
then
   task="$1"
   shift
else
   if [[ -e $1 ]] ;then
     task="add"
     input=$1
   else
      help=(1)
   fi
fi


#Process command line
while [[ $# -ge 1 ]]
do
  case "$1" in
              '-b' | '--bucket')
                bucket_name="$2"
                project_label="$bucket_name"
                shift
                shift
              ;;
              '-p' | '--project')
                os_project_name="$2"
                shift
                shift
              ;;
               '--path')
                options="$options --path $2"
                shift
                shift
              ;;
               '-l' | '--last')
                options="$options --last"
                shift
              ;;
              '-t' | '--target')
                target="$2"
                shift
                shift
              ;;
              '-f' | '--file')
                get_file="$2"
                shift
                shift
              ;;
              '-h' | '--help' | '-help')
                help=("1")
                shift
		          ;;

               *)
                if [[ $input == "" ]]
                then
                   input=("$1")
                   shift
                else 
                   options=("$options $1")
                   shift
                fi
              #echo No more switches
              ;;
    esac
done

if [[ $task == "add" ]]; then
  if [ ! -e $input ] ; then
     echo "File or directory $input does not exist!"
     exit 1
  fi
fi


if [[ $(which restic 2>/dev/null | wc -c) -eq 0 ]]
   then 
        echo "restic command not found!"
        echo ""
        echo "restic (https://restic.readthedocs.io) must be installed" 
        echo "and in command path in order to use this tool"
        echo ""
        return
fi


if [[ $help -eq 1 ]]; then
cat <<EOF

lumi-backup

lummi-backup tool provides easy to use command line interface to the Restic back up tool.
(https://restic.readthedocs.io/). lumi-backup automatically creates a project specific back up 
repository to the Lumi-O storage service at CSC and uses that for making cumulative back ups.

In order to use this tool, you must first open connection to Lumi-O storage service with
command:
   source $allas_conf_path --lumi


BACKUP OPERATIONS

lumi-backup can be used for following five operations:

  lumi-backup <file_name>  or
  lumi-backup add <file_name>       Add a new backup version (snapshot) of the given file 
                                    or directory to the back up repository.

  lumi-backup list                  Lists the snapshots saved to the repository. 
                                    Option: --last lists only the latest versions of different snapshots.
 
  lumi-backup files <snapshot_id>   List the files that the snapshot includes.

  lumi-backup find <query>          Find snapshots that contain file or directory that match the given query term.


  lumi-backup restore <snapshot_id>  Retrieves the data of the given snapshot to the local environment. 
                                     By default the stored data is restored to the local directory. Other locations can be 
                                     defined with -target option.
                                     Existing local files will not be overwritten. Only missing files will be retrieved.

  lumi-backup restore-overwrite <snapshot_id>    Retrieves the data of the given snapshot to the local environment. 
                                     By default the stored data is restored to the local directory. Other locations can be 
                                     defined with -target option.
                                     Existing local files will be overwritten.    

  lumi-backup restore-newer <snapshot_id>      Retrieves the data of the given snapshot to the local environment. 
                                     By default the stored data is restored to the local directory. Other locations can be 
                                     defined with -target option.
                                     Existing local files will be overwritten only if the file in the snapshot has a newer modification time.                               





  lumi-backup restore <snapshot_id> Retrieves the data of the given snapshot to the local environment. By default 
                                    the stored data is restored to the local directory. Other locations can be 
                                     defined with --target option.

  lumi-backup delete <snapshot_id>  Deletes a snapshot from the backup repository.

  lumi-backup dump <snapshot_id> -f <file>   Retrieve contents of a file in the snapshot.

  lumi-backup unlock                Remove Restic lock files.

  Extra options:
 
  -b, --bucket                        Use specific bucket for your repository. Note that this makes
                                     lumi-backup to use different separate repository instead of
                                     the default one.

  -t, --target                      Directory into which the data is restored.

  -l, --last                        In listing show only the latest version of each backup directory.

  --path                            only consider snapshots including this (absolute) path, 
                                    when snapshot ID "latest" is given

  -f, --file                        File to be retrieved with dump command


EOF
exit 0
fi

### Settings for S3  
if [[ -e  $HOME/.config/rclone/rclone.conf ]]; then
    endpoint_url="https://lumidata.eu"
    accesskey=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "access_key_id" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $1 == "lumi-o" ) print $2 }')
    secretaccesskey=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "secret_access_key" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $1 == "lumi-o" ) print $2 }')
    os_project_name=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "access_key_id" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $2 == "'$accesskey'" ) print $1 }' | grep "lumi-" | grep "private" | awk -F "-" '{print $2}')
    export AWS_DEFAULT_REGION=""
    export AWS_ACCESS_KEY_ID="$accesskey"
    export AWS_SECRET_ACCESS_KEY="$secretaccesskey"
else
  echo "Unable to find S3 credentials for Lumi."
  exit 1
fi


if [[ ${os_project_name} == "" ]]; then
      echo "Lumi project could not be defined!"
      echo "To fix this, run command:"
      echo "   source $allas_conf_path --lumi"
      exit 1
fi 

project_label=$(echo ${os_project_name} | sed -e s/"project_"/""/g)

#set default bucket name
if [[ $bucket_name == "" ]]; then
   bucket_name="${project_label}-backup"
fi

repository="s3:https://lumidata.eu/${bucket_name}"  


check_repo=$(rclone ls lumi-o:${bucket_name}/config | wc -l)
if [[ $check_repo -eq 0 ]]; then
    echo "Backup repository $repository does not exist."
    echo "Do you want to create it[y/n]?"
    read ans
    if [[ $ans != "y" ]]; then
        echo "exiting."
         exit 0
    fi   
    create_new=1
fi

if [[ $create_new -eq 1 ]]
then
  echo ""
  echo "Opening a new backup repository in $repository."
  echo ""
  echo "Do you want to define a password for the project (y/n)?"
  read ans
  if [[ $ans == "y" ]]; then
    echo "Please define password for backup repository $repository"
    echo "Use only letters and numbers in the password:"
    read passwd
    echo ""
    echo $passwd >  $HOME/.backup_passwd_${bucket_name}
    echo "Password stored to $HOME/.backup_passwd_${bucket_name}"
  else
    echo ${project_label} >  $HOME/.backup_passwd_${bucket_name}
  fi
   rclone mkdir lumi-o:"$bucket_name"
   restic init --repo $repository -p $HOME/.backup_passwd_${bucket_name} 
fi 


if [[ ! -e $HOME/.backup_passwd_${bucket_name} ]]
then
  echo "Password for restic repository: $repository not found in your home directory"
  echo "Is the repository using the default password (y/n)?"
  read ans
  if [[ $ans == "y" ]]; then
     echo ${project_label} >  $HOME/.backup_passwd_${bucket_name}
  else
    echo "Please give the password for backup repository $repository"
    read passwd
    echo ""
    echo $passwd >  $HOME/.backup_passwd_${bucket_name}
    echo "Password stored to $HOME/.backup_passwd_${bucket_name}"
  fi
fi 

if [[ $task == "add" ]]
then
  restic backup --repo $repository -p $HOME/.backup_passwd_${bucket_name} --tag $USER --pack-size $packsize $input
fi

if [[ $task == "list" ]]
then
  #echo "restic snapshots --repo $repository -p $HOME/.backup_passwd_${project_label} $input $options"
  restic snapshots --repo $repository -p $HOME/.backup_passwd_${bucket_name} $input $options
fi

if [[ $task == "files" ]]
then
  if [[ $input == "" ]]; then
     echo ""
     echo "No snapshot name defined for command: lumi-backup files."
     echo "Please give the snapshot name as a command line argument."
     echo ""
     exit 1
  fi
  #echo "restic snapshots --repo $repository -p $HOME/.backup_passwd_${project_label} $input $options"
  restic ls --repo $repository -p $HOME/.backup_passwd_${bucket_name} $input $options
fi

if [[ $task == "find" ]]
then
  echo "-------------------------------------------------------"
  if [[ $input == "" ]]; then
     echo "No query term defined for command: lumi-backup find"
     echo " Please give the query term as a command line argument."
     echo ""
     exit 1
  fi
  #echo "restic find --repo $repository -p $HOME/.backup_passwd_${project_label} $options"
  restic find --repo $repository -p $HOME/.backup_passwd_${bucket_name} $input $options > .find_list_$$
  numhits=$(grep -v "Found matching entries" .find_list_$$ | grep . | wc -l)
  numsn=$(grep "Found matching entries" .find_list_$$ | grep . | wc -l)
  cat  .find_list_$$
  echo ""
  echo "$numhits hits in $numsn snapshots found for query term: $input"
  rm -f  .find_lits_$$
fi

 
if [[ $task == "restore" ]]
then
  if [[ $input == "" ]] ; then
     echo "No snapshot name defined. Please give the snapshot name as a command line argument."
     echo ""
     exit 1
  fi
  if [[ $target == "./" ]]; then
     echo "Restoring snapshot $input to current directory"
  else
     echo "Restoring snapshot $input to directory: $target"
  fi
  echo "Only missing files will be downloaded. Existing local files will not be overwritten."
  echo ""
  if [[ $RESTIC_PASSWORD != "" ]]; then   
     restic restore --repo $repository --overwrite never $input --target $target $options
  else
     restic restore --repo $repository --overwrite never -p $HOME/.backup_passwd_${project_label} $input --target $target $options
  fi
fi

if [[ $task == "restore-overwrite" ]]
then
  if [[ $input == "" ]] ; then
     echo "No snapshot name defined. Please give the snapshot name as a command line argument."
     echo ""
     exit 1
  fi
  if [[ $target == "./" ]]; then
     echo "Restoring snapshot $input to current directory."
  else
     echo "Restoring snapshot $input to directory: $target"
  fi
  echo "All files from the snapshot will be downloaded. Existing local files will be overwritten."
  echo ""
  if [[ $RESTIC_PASSWORD != "" ]]; then  
    restic restore --repo $repository --overwrite always $input --target $target $options
  else 
    restic restore --repo $repository --overwrite always -p $HOME/.backup_passwd_${project_label} $input --target $target $options
  fi
fi
 
if [[ $task == "restore-newer" ]]
then
  if [[ $input == "" ]] ; then
     echo "No snapshot name defined. Please give the snapshot name as a command line argument."
     echo ""
     exit 1
  fi
    if [[ $target == "./" ]]; then
     echo "Restoring snapshot $input to current directory."
  else
     echo "Restoring snapshot $input to directory: $target"
  fi
  echo "Existing local files will be overwritten only if the time stamp in the snapshot is newer than in the local file."
  echo ""
  if [[ $RESTIC_PASSWORD != "" ]]; then 
     restic restore --repo $repository --overwrite if-newer $input --target $target $options
  else
     restic restore --repo $repository --overwrite if-newer -p $HOME/.backup_passwd_${project_label} $input --target $target $options
  fi   
fi

if [[ $task == "delete" ]]
then
  if [[ $input == "" ]]; then
     echo "No snapshot name defined. Please give the snapshot name as a command line argument."
     echo ""
     exit 1
  fi
  restic forget --prune --repo $repository -p $HOME/.backup_passwd_${bucket_name} $input 
fi 
 
if [[ $task == "unlock" ]]
then
  restic unlock --repo $repository -p $HOME/.backup_passwd_${bucket_name} 
fi 



if [[ $task == "dump" ]]
then
  if [[ $get_file == "" ]];then 
     echo "No file name defined. Please give the file name using command line option: --ile."
     echo ""
     exit 1
  fi

  if [[ $input == "" ]]; then
     echo "No snapshot name defined. Please give the snapshot name as a command line argument."
     echo ""
     exit 1
  fi
  restic dump --repo $repository -p $HOME/.backup_passwd_${bucket_name} $input $get_file
fi 


## Log disabled
##Execute log creation
#message="$0 $(date) allas-backup $task "
#printf '{"version": "1.1", "host": "%s", "short_message": "utility log", "full_message": "%s", "level": 6, "_user": "%d"}' $(hostname) "$message" $(id -u) >> $allas_log


##If log is a file and not a service then check permissions
#if [[ $(ls $allas_log 2> /dev/null | wc -l) -eq 1 ]]; then
#  if [[ $(ls -l $allas_log | awk '{print $3}') == $user ]]; then
#     chmod a+rwx  $allas_log
#  fi
#fi
exit 0
