#!/bin/bash
#
# This script sets evironment variables for s5cmd command.
# The values are obtained from local rclone configuration file.


#Check if rclone is available
if [[ $(which rclone 2> /dev/null | wc -l ) -ne 1 ]]; then
      echo ""
      echo "rclone is not available!"
      echo "Please install or activate rclone."
      exit 1
fi


#collect list of active s3 connections
remotes=()
for re in $(rclone listremotes --type s3)
do  
    rclone lsd  --max-depth 1 --contimeout 2s --low-level-retries 2 $re 2>/dev/null > /dev/null
    check=$?
    if [[ $check -eq 0 ]]; 
    then  
       remotes+=( $re )
    fi 
done  

#remotes=($(rclone listremotes --type s3))

case ${#remotes[@]} in
    0)  
      echo "No active S3 connections found."
      exit 1
      ;;
    *)
      echo "Please select the number of the S3 connection to be activated for s5cmd."
      select remote in "${remotes[@]}" "Quit"; do
           [[ -n "$remote" ]]&& break
      done
      ;; 
esac

remotename=${remote:0:-1}
echo $remotename

access_key_id=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "access_key_id" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk '{ if ( $1 == "'$remotename'" ) print $2 }')
#echo access_key:  $access_key_id
secret_access_key=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "secret_access_key" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk '{ if ( $1 == "'$remotename'" ) print $2 }')
#echo secret_key: $secret_access_key
endpoint=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "endpoint" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $1 == "'$remotename'" ) print $2 }')

endpoint=$( echo $endpoint | awk -F "/" '{print $NF}' )


export AWS_ACCESS_KEY_ID=$access_key_id
export AWS_SECRET_ACCESS_KEY=$secret_access_key
export AWS_PROFILE=default
export AWS_REGION=region-one
export S3_ENDPOINT_URL="https://"$endpoint

