#!/bin/bash

mkdir test_$$

echo "aaa" > test_$$/a.txt
echo "bbb" > test_$$/b.txt
echo "ccc" > test_$$/c.txt

#a-put
echo "Testing A commands"
object=$(a-put -b allastest_$$ test_$$ -s)
if [[ $object == "allastest_$$/test_$$.tar.zst" ]]; then
  echo "a-put OK"
else
  echo "a-put FAILED"
 # exit 1
fi
 
#a-list
t1=$(a-list allastest_$$)
if [[ $t1 == "test_$$.tar.zst" ]]; then
  echo "a-list OK"
else
  echo "a-list FAILED" 
  a-list  allastest_$$
fi

#a-info

if [[ $(a-info $object | grep -c "test_") -eq 5 ]]; then
  echo "a-info OK"
else
  echo "a-info FAILED"
fi

rm -rf test_$$

#a-get
a-get $object > /dev/null
if [[ $(ls  test_$$ | grep -c .txt) -eq 3 ]]; then
  echo "a-get OK"
else
  echo "a-get FAILED"
fi

a-delete -f  $object > /dev/null
a-delete --rmb  allastest_$$ -f > /dev/null

rm -rf test_$$

a=$(a-list allastest_$$ 2>&1 | tr -d "'")
if [[ $a == "Container allastest_$$ not found" ]]; then
   echo "a-delete OK"
else
   echo "a-delete FAILED"
fi
