#!/bin/bash

mkdir test_$$

echo "aaa" > test_$$/a.txt
echo "bbb" > test_$$/b.txt
echo "ccc" > test_$$/c.txt

#a_put
echo "Testing A commands"
object=$(a_put -b allastest_$$ test_$$ -s)
if [[ $object == "allastest_$$/test_$$.tar.zst" ]]; then
  echo "a_put OK"
else
  echo "a_put FAILED"
  exit 1
fi

#a_list
t1=$(a_list allastest_$$)
if [[ $t1 == "test_$$.tar.zst" ]]; then
  echo "a_list OK"
else
  echo "a_list FAILED" 
fi

#a_info

if [[ $(a_info $object | grep -c "test_") -eq 5 ]]; then
  echo "a_info OK"
else
  echo "a_info FAILED"
fi

rm -rf test_$$

#a_get
a_get $object > /dev/null
if [[ $(ls  test_$$ | grep -c .txt) -eq 3 ]]; then
  echo "a_get OK"
else
  echo "a_get FAILED"
fi

a_delete -f  $object > /dev/null
a_delete --rmb  allastest_$$ -f > /dev/null

rm -rf test_$$

a=$(a_list allastest_$$ 2>&1 | tr -d "'")
if [[ $a == "Container allastest_$$ not found" ]]; then
   echo "a_delete OK"
else
   echo "a_delete FAILED"
fi