#!/bin/sh
# This script disables some features of Nextcloud
# It is intended for making the Nextcloud less overloaded with features when you just need to test if a snap installed Nextcloud is good UI for a remote storage resource.
# Made for Nextcloud 20.0.1

# check that there is nextcloud.occ either in $PATH or in /var/lib/snapd/snap/bin/
OCC=nextcloud.occ
PROG_LOCATION=`/usr/bin/which $OCC 2>/dev/null`
if [ ! -e "$PROG_LOCATION" ]; then
	OCC="/var/lib/snapd/snap/bin/nextcloud.occ"
	if [ ! -e "$OCC" ]; then
		echo "Error: Can't find nextcloud.occ in \$PATH or in /var/lib/snapd/snap/bin/" >&2
		exit 1
	fi
fi

# The list of apps this script won't try to disable
PASS_APPS="accessibility bruteforcesettings cloud_federation_api dav federatedfilesharing files files_external files_sharing lookup_server_connector oauth2 password_policy provisioning_api settings twofactor_backupcodes viewer workflowengine"

# Loop though app listing
$OCC app:list \
| awk '{if (/^  *\- /) {sub(/^  *\- /,""); sub(/:.*/,""); print}} /^Disabled:/{exit}' \
| while read line
do
	disable=1
	for APP_NAME in $PASS_APPS
	do
		if [ "$APP_NAME" == "$line" ]; then
			disable=0
			break
		fi
	done

	if [ $disable -eq 1 ]; then
		$OCC app:disable "$line"
	fi
done

# Allow uploading only to the remote resource by making default quota to 0
$OCC config:app:set files default_quota --value="0"

# files_external is not enabled by default, enable it
$OCC app:enable files_external

# Disable some sharing options
$OCC config:app:set core shareapi_allow_links --value="no"
$OCC config:app:set core shareapi_allow_resharing --value="no"
$OCC config:app:set files_sharing incoming_server2server_share_enabled --value="no"
$OCC config:app:set files_sharing lookupServerEnabled --value="no"
$OCC config:app:set files_sharing lookupServerUploadEnabled --value="no"
$OCC config:app:set files_sharing outgoing_server2server_share_enabled --value="no"

# Set the max number of failed login attempts before account is blocked
$OCC config:app:set password_policy maximumLoginAttempts --value="5"

